// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAavBJxsCm8GhDPRl2qSvjOtjSboQuCPmo',
    appId: '1:37332990351:web:dc153059fd2d455181b3fa',
    messagingSenderId: '37332990351',
    projectId: 'twitterclone-969d2',
    authDomain: 'twitterclone-969d2.firebaseapp.com',
    storageBucket: 'twitterclone-969d2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB61PvRNXf1hqVFjyr8xaRp5CzjkSupEdU',
    appId: '1:37332990351:android:97d6d99436ba208a81b3fa',
    messagingSenderId: '37332990351',
    projectId: 'twitterclone-969d2',
    storageBucket: 'twitterclone-969d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdMFfZTSg93PVuA5EjoEkRC25i3yPE6Gg',
    appId: '1:37332990351:ios:729a5f941a5d906681b3fa',
    messagingSenderId: '37332990351',
    projectId: 'twitterclone-969d2',
    storageBucket: 'twitterclone-969d2.appspot.com',
    iosClientId: '37332990351-dn4h16e2cid8bps15005eeghtm5cq3bl.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdMFfZTSg93PVuA5EjoEkRC25i3yPE6Gg',
    appId: '1:37332990351:ios:332c0f521898bf7881b3fa',
    messagingSenderId: '37332990351',
    projectId: 'twitterclone-969d2',
    storageBucket: 'twitterclone-969d2.appspot.com',
    iosClientId: '37332990351-hu7qnoh5s8gtir09afrji7mtd52fsvhl.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitter.RunnerTests',
  );
}
